<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Sesi Saya_searchMentor</name>
   <tag></tag>
   <elementGuidId>9975bed8-28e8-4ada-8bde-9d416f93dfcc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='searchMentor']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#searchMentor</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>24a8a295-ce89-44b9-8d4b-44a91424f311</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-input</value>
      <webElementGuid>a6cdb3ab-96b5-4ab9-89de-be58a4635726</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Cari berdasarkan nama, perusahaan, peran, industri, universitas, jurusan, topik</value>
      <webElementGuid>83a88a75-0e1e-48b6-be58-a78dc89756c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>searchMentor</value>
      <webElementGuid>9df809b1-2f91-451f-a9f6-91c91c522f00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d6755008-6ee8-441f-baef-420c99676aca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;searchMentor&quot;)</value>
      <webElementGuid>be5a3e5b-baa0-43ab-a438-46616f6e62ae</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='searchMentor']</value>
      <webElementGuid>40bcbb79-2f5b-4a8e-bbb3-ba7a983bb303</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div[3]/main/div[2]/main/div/div/div/div[2]/div/form/span/input</value>
      <webElementGuid>58f8a784-c3fa-476d-aa07-1ea24662161d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>26fa8757-5103-4190-af2a-271e7e7b2cf1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Cari berdasarkan nama, perusahaan, peran, industri, universitas, jurusan, topik' and @id = 'searchMentor' and @type = 'text']</value>
      <webElementGuid>585ad826-98b9-44b3-a143-2596ad49a2d1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
