<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_C-level</name>
   <tag></tag>
   <elementGuidId>46c5e2a3-e610-4f32-b8a1-869cfacfc78f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='experience-form-list']/div/div/div/div[2]/form/div[2]/div[4]/div/div/div/div/div/div/div/div[2]/div/div/div/div[2]/div/div/div/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.ant-select-item.ant-select-item-option.ant-select-item-option-active</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>c3af8944-2575-4a7a-a926-8ca9e86e1dad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>ce22cba0-85bc-4aae-b467-30efb182d2d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-select-item ant-select-item-option ant-select-item-option-active</value>
      <webElementGuid>6c500872-196e-4fc2-8de9-1cb8417734ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>C-level</value>
      <webElementGuid>87ca2d92-bc63-4011-8643-3220a89ec572</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>C-level</value>
      <webElementGuid>e8be6c15-ae5e-4c2a-974b-b731974fe37f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;experience-form-list&quot;)/div[@class=&quot;ant-spin-nested-loading&quot;]/div[@class=&quot;ant-spin-container&quot;]/div[@class=&quot;overflow-hidden rounded-lg border border-neutral-100 shadow-[3px_3px_0px_rgba(0,0,0,0.1)] dropdown_system_v1__hvsTx OnboardingExperienceForm_onboarding_experience_form__ibdfE&quot;]/div[@class=&quot;bg-white px-4 pt-4 pb-6 lg:px-[22px] lg:pb-5&quot;]/form[@class=&quot;ant-form ant-form-horizontal&quot;]/div[@class=&quot;grid h-full w-full grid-cols-1 items-start gap-3 lg:grid-cols-[auto_288px]&quot;]/div[@class=&quot;Select_system_v1__KvWIf w-full Select_system_select_sm__TWVOd&quot;]/div[@class=&quot;relative&quot;]/div[@class=&quot;ant-form-item FormItem_style_v1__95_Jx m-0&quot;]/div[@class=&quot;ant-row ant-form-item-row&quot;]/div[@class=&quot;ant-col ant-form-item-control&quot;]/div[@class=&quot;ant-form-item-control-input&quot;]/div[@class=&quot;ant-form-item-control-input-content&quot;]/div[@class=&quot;ant-select ant-select-in-form-item ant-select-focused ant-select-single ant-select-show-arrow ant-select-open ant-select-show-search&quot;]/div[2]/div[1]/div[@class=&quot;ant-select-dropdown dropdown_popup_single__76HQ5 ant-select-dropdown-placement-bottomLeft&quot;]/div[1]/div[@class=&quot;rc-virtual-list&quot;]/div[@class=&quot;rc-virtual-list-holder&quot;]/div[1]/div[@class=&quot;rc-virtual-list-holder-inner&quot;]/div[@class=&quot;ant-select-item ant-select-item-option ant-select-item-option-active&quot;]</value>
      <webElementGuid>55ae4104-648f-4d24-8cf8-d828ffd81bb5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='experience-form-list']/div/div/div/div[2]/form/div[2]/div[4]/div/div/div/div/div/div/div/div[2]/div/div/div/div[2]/div/div/div/div[2]</value>
      <webElementGuid>3e913d3e-8eee-4462-87b3-49099b74c8d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Associate / Officer'])[1]/following::div[1]</value>
      <webElementGuid>547f53f9-87f4-4a52-bdf6-f5d7afa9a133</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cth : Manajer'])[1]/following::div[15]</value>
      <webElementGuid>778896c2-0216-4d9a-9fb0-7f69ce5af685</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Director'])[1]/preceding::div[2]</value>
      <webElementGuid>d405bf9f-2af0-48de-8826-16ee59ebde51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div[2]/div/div/div/div[2]</value>
      <webElementGuid>01a1f85c-25a9-4e70-9cd8-f248050801d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@title = 'C-level' and (text() = 'C-level' or . = 'C-level')]</value>
      <webElementGuid>028fa03a-ca74-464c-93e0-72e76c3eb65b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
