<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_WhatsApp Number_whatsapp</name>
   <tag></tag>
   <elementGuidId>ae77c823-7cab-49db-845d-31c2e3cf5215</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='whatsapp']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#whatsapp</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4383c78f-c5e4-4841-ac4d-8e9ec8eee74e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Start with country code ex. 62</value>
      <webElementGuid>38f1c04b-e9f0-41cf-9459-96641062756c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-input py-0 rounded-md border border-neutral-15 bg-neutral-5 hover:border-tertiary-violet-50 focus:border-tertiary-violet-50 active:border-tertiary-violet-50 placeholder:text-neutral-30 text-neutral-100 text-[11px] h-[33px] focus:shadow-none px-[14px] md:px-4 placeholder:!text-neutral-60</value>
      <webElementGuid>0ed0531f-d73f-41d1-8791-8a4cba82f149</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1108f3ba-e6fa-4f35-8166-9c9b5b6ad195</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>15</value>
      <webElementGuid>9d69d8f0-a3c1-4ef7-ba1d-47595166c76e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>whatsapp</value>
      <webElementGuid>6dd9c64f-924a-4da9-a5c6-1e3ca3b77951</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;whatsapp&quot;)</value>
      <webElementGuid>6b481198-81b8-45c2-8730-c0dae32456df</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='whatsapp']</value>
      <webElementGuid>6ad35d34-53c1-470b-b0f1-699516ebf344</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/div/div[3]/form/div/div[3]/div[2]/div[2]/div[2]/div/div/div/div/div/div/input</value>
      <webElementGuid>6450f881-870d-4693-9711-01ca78eef487</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>1d4a43ae-dd0e-4fbf-ab36-14df2410a097</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Start with country code ex. 62' and @type = 'text' and @id = 'whatsapp']</value>
      <webElementGuid>63475966-2218-4a97-972e-1fceb92983bc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
