<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Konfirmasi Kata Sandi_passwordConfirmation</name>
   <tag></tag>
   <elementGuidId>eeedf3a9-f544-46cc-b9ec-ce02aef77eaf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='passwordConfirmation']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#passwordConfirmation</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>58c6be0b-9139-483a-bfbf-03512d3c7b8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Atur kata sandi Anda di sini</value>
      <webElementGuid>0873c143-6050-4170-b9f9-832a3d3d010e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>f32d5abd-f1a5-4ac0-877d-f3ea02ab4f8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>passwordConfirmation</value>
      <webElementGuid>94899e52-3275-45c9-9e55-a30a694f0e7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>a6c9074c-c07f-45b5-b3bd-3e793b8a8c98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-input</value>
      <webElementGuid>6e9cf6b6-4f56-42e8-aba7-6f8529047a5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;passwordConfirmation&quot;)</value>
      <webElementGuid>fb8f708f-207d-44db-9fce-9710f2e4c889</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='passwordConfirmation']</value>
      <webElementGuid>c6225020-5a5b-440a-a9f2-217ec5e25da8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/div/div[3]/form/div[2]/div/div/div/div/div/span/input</value>
      <webElementGuid>bbcfdf0a-e68a-4321-8734-082dbbbed51c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/span/input</value>
      <webElementGuid>a5f6fde6-4474-4fdd-a0b9-c2b998444079</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Atur kata sandi Anda di sini' and @type = 'password' and @id = 'passwordConfirmation']</value>
      <webElementGuid>d6d2ddc5-56a3-4123-98cd-facbc779a658</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
