<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Tanggal Selesai_endDate</name>
   <tag></tag>
   <elementGuidId>4ae26e21-fdce-4fbd-8e0e-e04897c380b5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='endDate']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#endDate</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f572425c-3884-4f4a-ab48-30f5ce2ff1ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>2beab13f-d19f-47cc-a49a-59c7e7a7358c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>MM/YYYY</value>
      <webElementGuid>4230fefd-5391-4f6b-b5a9-874a3e1baa17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-input px-4 py-0 rounded-md border border-neutral-15 bg-neutral-5 hover:border-tertiary-violet-50 focus:border-tertiary-violet-50 active:border-tertiary-violet-50 h-8 text-xs placeholder:text-neutral-60 disabled:border-neutral-15 disabled:bg-neutral-15 disabled:text-neutral-80</value>
      <webElementGuid>aaaa7efd-f9d7-497d-beb8-b1102169c337</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>7</value>
      <webElementGuid>9997be90-5cf6-4dfc-b3af-cb3f114a9369</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>endDate</value>
      <webElementGuid>68f3967e-ab24-49af-9cb9-0d8e06e38d54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>cf8191d2-0a29-4c74-84ae-22a773825baf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>9b7d1037-5609-47ab-88e0-f16d4f40322c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;endDate&quot;)</value>
      <webElementGuid>8bb37983-18fb-437b-b42a-251300645c63</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='endDate']</value>
      <webElementGuid>71325ade-ee97-42a7-b98b-12a9d7f14b17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='experience-form-list']/div/div/div/div[2]/form/div[2]/div[10]/div/div/div/div/div/input</value>
      <webElementGuid>ad0aa988-00f7-4ed9-a46a-b2450be15156</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div/div/div/div/div/input</value>
      <webElementGuid>9fddfe76-bcc2-4705-bd2b-543251d45e14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'MM/YYYY' and @id = 'endDate' and @type = 'text']</value>
      <webElementGuid>88ee9e7e-ffae-49dc-80d8-edec93f8c3ac</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
