<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_name_fullName</name>
   <tag></tag>
   <elementGuidId>a2583711-8c93-462c-a75b-9713c08a9d95</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='fullName']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#fullName</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1550410d-0181-4aba-bb4d-a17abebe0213</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Your full name here please</value>
      <webElementGuid>7f36b79d-596f-4782-a2b0-551948fff1ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-input px-4 py-0 rounded-md border border-neutral-15 bg-neutral-5 hover:border-tertiary-violet-50 focus:border-tertiary-violet-50 active:border-tertiary-violet-50 placeholder:text-neutral-30</value>
      <webElementGuid>7be00a93-e8be-49e6-bb08-835f050b8ca8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>fullName</value>
      <webElementGuid>4ecaa4ba-33ff-412b-84c6-284455e02943</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>66647eeb-7aff-4429-b366-c0df3be512ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5bff82aa-4403-4a90-bb84-00f21fdc24c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fullName&quot;)</value>
      <webElementGuid>f9de093a-6b80-4298-9a1d-d6c997ef324b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='fullName']</value>
      <webElementGuid>49f5a598-aa54-44c1-a572-04782de7cfca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/div/form/div/div/div/div/div/div/div/input</value>
      <webElementGuid>c28f05bb-e618-4ad3-97d0-f365f3ee0c2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>81d9ec12-a243-4429-9447-cadb0ee4c9e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Your full name here please' and @id = 'fullName' and @type = 'text']</value>
      <webElementGuid>a08aad59-2a8c-4883-9ac0-a218eccde8de</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
