<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Selanjutnya_1_2</name>
   <tag></tag>
   <elementGuidId>9229be69-10eb-49d8-94ae-8daf38d13c05</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='experience-selection']/div[5]/button[2]/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>c43b472b-1662-41d5-b5ac-52c167bfc429</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Selanjutnya</value>
      <webElementGuid>acd74fc2-b858-459e-8e2d-fd526702936f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;experience-selection&quot;)/div[@class=&quot;z-30 flex w-full flex-col items-center justify-center gap-1 px-[34px] py-[14px] md:flex-row !px-8 md:px-0 pt-[42px] pb-6 md:pb-[90px]&quot;]/button[@class=&quot;ant-btn ant-btn-default order-1 w-full md:order-2 md:w-[176px] after:!shadow-none flex items-center justify-center font-bold active:!shadow-[3px_3px_0px_#000000] shadow-[3px_3px_0px_#000000] disabled:shadow-[3px_3px_0px_#000000] disabled:hover:shadow-[3px_3px_0px_#000000] disabled:cursor-not-allowed disabled:border-black disabled:bg-neutral-30 disabled:text-white disabled:hover:border-black disabled:hover:bg-neutral-30 disabled:hover:text-white border border-black hover:border-black focus:border-black active:border-black bg-tertiary-violet-50 text-white hover:bg-tertiary-violet-50 hover:text-white focus:bg-tertiary-violet-50 focus:text-white active:bg-tertiary-violet-50 active:text-white rounded-[71px] h-9 text-xs lg:h-11 lg:text-base&quot;]/span[1]</value>
      <webElementGuid>72303807-216a-4110-a72a-334e7dca1e27</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='experience-selection']/div[5]/button[2]/span</value>
      <webElementGuid>c25ea218-1a9c-4eb6-9a98-054810460126</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kembali'])[1]/following::span[1]</value>
      <webElementGuid>5e939eb3-fec4-4bc4-b10a-ca3c992ddaad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Masih bekerja pada posisi ini'])[1]/following::span[2]</value>
      <webElementGuid>3926cbf0-aad1-46a8-a9e2-9f7cd965b169</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Selanjutnya']/parent::*</value>
      <webElementGuid>8f491e6a-8705-4eba-a3d5-9fcf66c239a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/button[2]/span</value>
      <webElementGuid>5052596e-78af-41a4-ae22-20cb94debc84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Selanjutnya' or . = 'Selanjutnya')]</value>
      <webElementGuid>10f6f488-019b-488e-8a71-0d9e95a7cccb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
