<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Selanjutnya_1</name>
   <tag></tag>
   <elementGuidId>5d157ca3-f64d-4c91-90cb-755d176d3e4f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/main/div/div[5]/button[2]/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>3e14f9eb-454b-42e6-9e95-110d110fb1ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Selanjutnya</value>
      <webElementGuid>fc911ca2-7f1f-43b2-b0a1-12d92d53cc7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/main[@class=&quot;relative min-h-screen bg-neutral-5&quot;]/div[@class=&quot;min-h-screen min-w-screen px-4 md:px-0 PersonalIDCardForm_personal_id_card_form__fWHgm&quot;]/div[@class=&quot;z-30 flex w-full flex-col items-center justify-center gap-1 py-[14px] md:flex-row absolute left-0 px-8 pt-10 pb-6 md:px-0 md:pt-[60px] md:pb-[58px] !border-none !shadow-none bg-neutral-5&quot;]/button[@class=&quot;ant-btn ant-btn-default order-1 w-full md:order-2 md:w-[176px] after:!shadow-none flex items-center justify-center font-bold active:!shadow-[3px_3px_0px_#000000] shadow-[3px_3px_0px_#000000] disabled:shadow-[3px_3px_0px_#000000] disabled:hover:shadow-[3px_3px_0px_#000000] disabled:cursor-not-allowed disabled:border-black disabled:bg-neutral-30 disabled:text-white disabled:hover:border-black disabled:hover:bg-neutral-30 disabled:hover:text-white border border-black hover:border-black focus:border-black active:border-black bg-tertiary-violet-50 text-white hover:bg-tertiary-violet-50 hover:text-white focus:bg-tertiary-violet-50 focus:text-white active:bg-tertiary-violet-50 active:text-white rounded-[71px] h-9 text-xs lg:h-11 lg:text-base&quot;]/span[1]</value>
      <webElementGuid>9f4ed372-d157-4415-8760-843c00fe1778</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/div/div[5]/button[2]/span</value>
      <webElementGuid>56b50198-f625-4f96-b696-696a651c67c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kembali'])[1]/following::span[1]</value>
      <webElementGuid>645bc855-f690-48eb-8be5-9ce0f0234a08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Freshgrad'])[1]/following::span[4]</value>
      <webElementGuid>8e320ccb-5419-40aa-a220-a195b3fd0ec7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='activelyLooking'])[1]/preceding::span[1]</value>
      <webElementGuid>0467e1b8-20f7-440d-bd94-9525ff85c4b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='openOpportunity'])[1]/preceding::span[1]</value>
      <webElementGuid>710e62a6-1b61-45f7-8936-f9a3c4bf3495</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Selanjutnya']/parent::*</value>
      <webElementGuid>2ee52a07-a8ee-4021-846b-df863697d999</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]/span</value>
      <webElementGuid>b551932b-f1ac-4a1c-adc7-d7f3ba604bcb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Selanjutnya' or . = 'Selanjutnya')]</value>
      <webElementGuid>067ec35a-e79e-4ba2-b30c-b79803ef196e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
