<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Selanjutnya</name>
   <tag></tag>
   <elementGuidId>1dc3e2f6-10b9-4d5f-847a-57091325262d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/main/div/div[4]/button[2]/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>502393d6-1834-4363-af0c-00701ee7b908</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Selanjutnya</value>
      <webElementGuid>13e9c79a-5cac-4edf-b1bd-84a469ffa7aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/main[@class=&quot;relative min-h-screen bg-neutral-5&quot;]/div[@class=&quot;flex min-h-screen w-full flex-col px-[25px] md:px-0&quot;]/div[@class=&quot;z-30 flex w-full flex-col items-center justify-center gap-1 px-[34px] py-[14px] md:flex-row !px-8 absolute right-0 bottom-0 left-0 pb-6 md:px-0 md:pb-[90px] !border-none !shadow-none bg-neutral-5&quot;]/button[@class=&quot;ant-btn ant-btn-default order-1 w-full md:order-2 md:w-[176px] after:!shadow-none flex items-center justify-center font-bold active:!shadow-[3px_3px_0px_#000000] shadow-[3px_3px_0px_#000000] disabled:shadow-[3px_3px_0px_#000000] disabled:hover:shadow-[3px_3px_0px_#000000] disabled:cursor-not-allowed disabled:border-black disabled:bg-neutral-30 disabled:text-white disabled:hover:border-black disabled:hover:bg-neutral-30 disabled:hover:text-white border border-black hover:border-black focus:border-black active:border-black bg-tertiary-violet-50 text-white hover:bg-tertiary-violet-50 hover:text-white focus:bg-tertiary-violet-50 focus:text-white active:bg-tertiary-violet-50 active:text-white rounded-[71px] h-9 text-xs lg:h-11 lg:text-base&quot;]/span[1]</value>
      <webElementGuid>1475ec91-07d8-4dab-afa6-26ccb72d121e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/div/div[4]/button[2]/span</value>
      <webElementGuid>09258793-04cc-4068-a6fd-0357c5b26e0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kembali'])[1]/following::span[1]</value>
      <webElementGuid>d09da699-63fe-48f4-b63b-e900232343fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='name'])[1]/following::span[2]</value>
      <webElementGuid>5d8020cb-9884-454f-aeb4-25cf24bdfdac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Selanjutnya']/parent::*</value>
      <webElementGuid>7b91e556-4007-4653-bae2-20a51316338b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]/span</value>
      <webElementGuid>c5fef24b-82c7-4f33-999f-c34c7bb86995</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Selanjutnya' or . = 'Selanjutnya')]</value>
      <webElementGuid>9144c99f-7b3c-4edf-b79a-df1bd50cb2af</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
