<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Mentoring</name>
   <tag></tag>
   <elementGuidId>4fbbf76a-713c-4654-9694-a2bc69f8863c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='header-navbar']/div/div/div/div/li[2]/div/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>d209508e-67dd-4b49-96cc-f8db423efca7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>inline-block py-1 text-xs !font-semibold text-white !decoration-2 !underline-offset-4 hover:!text-gray-200 hover:underline</value>
      <webElementGuid>706f47de-1cba-4510-bbb4-cec07c96f12d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/mentoring</value>
      <webElementGuid>93e16acb-a7ce-4e22-b1aa-38a9f7030ae5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Mentoring</value>
      <webElementGuid>4b9701c9-ea60-4319-803a-32b8ede9ba0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;header-navbar&quot;)/div[@class=&quot;mx-auto flex w-full max-w-[1440px] items-center justify-between px-4 py-2 xl:px-8&quot;]/div[@class=&quot;flex items-center&quot;]/div[@class=&quot;ml-[14px] hidden lg:block&quot;]/div[@class=&quot;relative flex w-full items-center gap-4&quot;]/li[@class=&quot;relative flex&quot;]/div[@class=&quot;LinkItem_navbar_link_item__Toizn&quot;]/a[@class=&quot;inline-block py-1 text-xs !font-semibold text-white !decoration-2 !underline-offset-4 hover:!text-gray-200 hover:underline&quot;]</value>
      <webElementGuid>31a3c5d8-913d-40b8-b6ba-b7a75da5adae</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='header-navbar']/div/div/div/div/li[2]/div/a</value>
      <webElementGuid>3b612cf8-deb9-417c-a004-9a361f3acc33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Mentoring')]</value>
      <webElementGuid>d3bd6879-b17f-43ac-9ae8-7be842302619</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Loker'])[1]/following::a[1]</value>
      <webElementGuid>74aa3d2b-e0b8-4598-bf0d-95ca55c24239</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Perusahaan'])[1]/preceding::a[1]</value>
      <webElementGuid>870e1e28-6c69-4aaf-be27-8b1658e9073d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Events'])[1]/preceding::a[2]</value>
      <webElementGuid>c9f9823b-4ace-4f82-8153-87a08b4fe9c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Mentoring']/parent::*</value>
      <webElementGuid>7920d515-359b-4c9e-afa8-31614df0a8b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/mentoring')]</value>
      <webElementGuid>2b294138-21bd-463c-81e0-4ba9b950d261</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/div/a</value>
      <webElementGuid>4ac03e52-84f5-4efd-bf83-01bc8c996e99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/mentoring' and (text() = 'Mentoring' or . = 'Mentoring')]</value>
      <webElementGuid>7b57b1b1-cab0-422c-b0e2-4579041c3f2d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
