<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_LokerMentoringPerusahaanEventsAI CV Ana_a5e262</name>
   <tag></tag>
   <elementGuidId>2883ae5f-8e56-445d-93db-f5b14df60b92</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='header-navbar']/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>2103283a-7684-444e-977b-925bf8c6ad84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mx-auto flex w-full max-w-[1440px] items-center justify-between px-4 py-2 xl:px-8</value>
      <webElementGuid>9a91bfe3-b157-4655-9faa-fb9e061b6f1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>LokerMentoringPerusahaanEventsAI CV Analyzer IDN</value>
      <webElementGuid>8447e9bb-532c-4edc-a844-51aeec71b53d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;header-navbar&quot;)/div[@class=&quot;mx-auto flex w-full max-w-[1440px] items-center justify-between px-4 py-2 xl:px-8&quot;]</value>
      <webElementGuid>76daad79-f7c4-4b7b-8459-dfe02807ef76</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='header-navbar']/div</value>
      <webElementGuid>85e8b176-3cb1-4567-aa0a-a64e8f78f9bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//header/div/div</value>
      <webElementGuid>a97ca758-f39f-49f2-803d-3b34deedfe44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'LokerMentoringPerusahaanEventsAI CV Analyzer IDN' or . = 'LokerMentoringPerusahaanEventsAI CV Analyzer IDN')]</value>
      <webElementGuid>7655ed33-718b-4918-b84d-0bdd5247caf9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
