<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_astreaAdministration at PT Pencari Cint_c7367b</name>
   <tag></tag>
   <elementGuidId>8fcbc18f-634e-47b2-8058-87c21d350559</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div[3]/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>fd98a68f-5776-4827-b14e-37667278ab4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mt-[76px] w-full xl:mx-auto xl:max-w-[1162px]</value>
      <webElementGuid>af0c44a6-56d9-48ab-916a-e2229f21ad8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>astreaAdministration at PT Pencari Cinta SejatiPreferensi Karier SayaInformasi UmumCV &amp; PortfolioPendaftaran SayaPekerjaan Tersimpan0Ubah Kata SandiPengalaman &amp; PreferensiPengalaman Kerja+  Tambah1AdministrationC-level • PT Pencari Cinta Sejati • Missing Industry01/2016 – 01/2025 (9 years)Pengalaman Organisasi+  TambahPengalaman organisasi Anda akan ditampilkan di sini.Sertifikasi / Penghargaan+  TambahSertifikasi / penghargaan Anda akan ditampilkan di sini.Preferensi KarierBagikan Profil Saya kepada RekruterRekruter dapat melihat profil Anda dan menghubungi Anda untuk peluang pekerjaan yang menarikStatus Mencari KerjaDipekerjakan, tetapi terbuka untuk peluang yang lebih menarikBerapa nominal gaji terendah yang akan Anda ajukan?RpPreferensi PosisiAdministration0+ Keterampilan Keahlian The #1 factor for more outreach from recruitersPreferensi Pengaturan Pekerjaan Pilih tipe tempat kerjaTingkat PengalamanFreshgradSembunyikan Profil Saya dari Perusahaan Ini Pilih PerusahaanJeda Notifikasi Email (1 Tahun)Tidak</value>
      <webElementGuid>7ab21a2e-25c2-44be-8b46-5139479644af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;flex min-h-screen max-w-screen flex-col&quot;]/div[@class=&quot;mt-[76px] w-full xl:mx-auto xl:max-w-[1162px]&quot;]</value>
      <webElementGuid>48c04d36-9bce-410f-ae3a-688229aee46f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div[3]/div</value>
      <webElementGuid>5d30979a-28a1-4a36-bd6a-1eaf9052b022</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AI CV Analyzer'])[1]/following::div[5]</value>
      <webElementGuid>6acda704-fcd8-47f1-bc83-3564bdcce8cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Events'])[1]/following::div[6]</value>
      <webElementGuid>4a689ad6-4487-4a69-8176-99a2468d8ce6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[3]/div</value>
      <webElementGuid>72a40c73-1a48-443f-b96b-8fb233d1ef75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'astreaAdministration at PT Pencari Cinta SejatiPreferensi Karier SayaInformasi UmumCV &amp; PortfolioPendaftaran SayaPekerjaan Tersimpan0Ubah Kata SandiPengalaman &amp; PreferensiPengalaman Kerja+  Tambah1AdministrationC-level • PT Pencari Cinta Sejati • Missing Industry01/2016 – 01/2025 (9 years)Pengalaman Organisasi+  TambahPengalaman organisasi Anda akan ditampilkan di sini.Sertifikasi / Penghargaan+  TambahSertifikasi / penghargaan Anda akan ditampilkan di sini.Preferensi KarierBagikan Profil Saya kepada RekruterRekruter dapat melihat profil Anda dan menghubungi Anda untuk peluang pekerjaan yang menarikStatus Mencari KerjaDipekerjakan, tetapi terbuka untuk peluang yang lebih menarikBerapa nominal gaji terendah yang akan Anda ajukan?RpPreferensi PosisiAdministration0+ Keterampilan Keahlian The #1 factor for more outreach from recruitersPreferensi Pengaturan Pekerjaan Pilih tipe tempat kerjaTingkat PengalamanFreshgradSembunyikan Profil Saya dari Perusahaan Ini Pilih PerusahaanJeda Notifikasi Email (1 Tahun)Tidak' or . = 'astreaAdministration at PT Pencari Cinta SejatiPreferensi Karier SayaInformasi UmumCV &amp; PortfolioPendaftaran SayaPekerjaan Tersimpan0Ubah Kata SandiPengalaman &amp; PreferensiPengalaman Kerja+  Tambah1AdministrationC-level • PT Pencari Cinta Sejati • Missing Industry01/2016 – 01/2025 (9 years)Pengalaman Organisasi+  TambahPengalaman organisasi Anda akan ditampilkan di sini.Sertifikasi / Penghargaan+  TambahSertifikasi / penghargaan Anda akan ditampilkan di sini.Preferensi KarierBagikan Profil Saya kepada RekruterRekruter dapat melihat profil Anda dan menghubungi Anda untuk peluang pekerjaan yang menarikStatus Mencari KerjaDipekerjakan, tetapi terbuka untuk peluang yang lebih menarikBerapa nominal gaji terendah yang akan Anda ajukan?RpPreferensi PosisiAdministration0+ Keterampilan Keahlian The #1 factor for more outreach from recruitersPreferensi Pengaturan Pekerjaan Pilih tipe tempat kerjaTingkat PengalamanFreshgradSembunyikan Profil Saya dari Perusahaan Ini Pilih PerusahaanJeda Notifikasi Email (1 Tahun)Tidak')]</value>
      <webElementGuid>350845d8-98c1-406b-bdfd-ac4352ab6df3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
