<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Optional, max. 1MB_mentor-onboarding__d79753</name>
   <tag></tag>
   <elementGuidId>d4fcc22a-d829-4078-9531-366caf279602</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='mentor-onboarding_invitationCode']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mentor-onboarding_invitationCode</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a1a699ad-6acc-405d-89ea-b5a6ba6f3282</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Invitation Code (Optional)</value>
      <webElementGuid>25df756e-1b22-4398-a5ed-5c806c927130</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-input py-0 rounded-md border border-neutral-15 bg-neutral-5 hover:border-tertiary-violet-50 focus:border-tertiary-violet-50 active:border-tertiary-violet-50 placeholder:text-neutral-30 text-neutral-100 text-[11px] h-[33px] focus:shadow-none px-[14px] md:px-4 placeholder:!text-neutral-60</value>
      <webElementGuid>2d4980c8-d8cb-4809-adb9-f84b73b8dbaa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3c406ef2-61f2-42f3-adaf-b755df403db4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mentor-onboarding_invitationCode</value>
      <webElementGuid>89a82d20-b9e5-46f9-9742-62c6d92955cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mentor-onboarding_invitationCode&quot;)</value>
      <webElementGuid>b9a2a57f-d5c1-4416-982d-a6f3b9903400</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='mentor-onboarding_invitationCode']</value>
      <webElementGuid>7695612b-9425-422c-b908-fbe9191fbe32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='mentor-onboarding']/div/div[3]/div[2]/div/div[6]/div/div/div/div/div/input</value>
      <webElementGuid>5d8ab8fb-fdb0-41d5-80b8-2c966b2dd2f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/div/div/div/input</value>
      <webElementGuid>f18193ee-a738-4530-8475-4b603b2945f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Invitation Code (Optional)' and @type = 'text' and @id = 'mentor-onboarding_invitationCode']</value>
      <webElementGuid>980bcb6f-fcff-4bcf-9cf6-7631ea21d0e2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
