<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Optional, max. 1MB_mentor-onboarding__048753</name>
   <tag></tag>
   <elementGuidId>2c5418b6-c5a9-4f07-8d6e-6984430bfe58</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='mentor-onboarding_linkedInUrl']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mentor-onboarding_linkedInUrl</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b21e1fa4-6aa9-4ffa-a819-edbbb3fd4ceb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>LinkedIn URL (Opsional)</value>
      <webElementGuid>88dd8963-0608-413f-bacb-f805de0b8fea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-input py-0 rounded-md border border-neutral-15 bg-neutral-5 hover:border-tertiary-violet-50 focus:border-tertiary-violet-50 active:border-tertiary-violet-50 placeholder:text-neutral-30 text-neutral-100 text-[11px] h-[33px] focus:shadow-none px-[14px] md:px-4 placeholder:!text-neutral-60</value>
      <webElementGuid>0c4e8f37-ca6f-48b2-8000-22319fb5288c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>08af6990-f192-4556-877d-973401d2b5bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mentor-onboarding_linkedInUrl</value>
      <webElementGuid>d32ca46c-f906-4a00-b785-e5153e26a1ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mentor-onboarding_linkedInUrl&quot;)</value>
      <webElementGuid>8d59396f-5713-4dbe-9b62-fc78bd03a015</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='mentor-onboarding_linkedInUrl']</value>
      <webElementGuid>77136143-ef2b-4eb6-be3d-1374235da50e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='mentor-onboarding']/div/div[3]/div[2]/div/div[4]/div/div/div/div/div/input</value>
      <webElementGuid>02ede7ad-2afe-4f75-bad4-97da0aa5e8bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/div/div/input</value>
      <webElementGuid>0b4f8553-3e80-48b6-a517-e01cadb4827c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'LinkedIn URL (Opsional)' and @type = 'text' and @id = 'mentor-onboarding_linkedInUrl']</value>
      <webElementGuid>87d7533b-b02a-421b-97b8-5154b8b2dd0b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
