<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Optional, max. 1MB_mentor-onboarding__18dd99</name>
   <tag></tag>
   <elementGuidId>b97c8232-ad73-4491-a2c4-78cda5a853f2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='mentor-onboarding_whatsapp']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mentor-onboarding_whatsapp</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>72cdbb78-fcf1-423d-8b9e-b7db9454d26d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Whatsapp (mulai dengan kode negara, cth: 62)</value>
      <webElementGuid>2426a187-4f71-4add-8ea1-8f1370f62456</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-input py-0 rounded-md border border-neutral-15 bg-neutral-5 hover:border-tertiary-violet-50 focus:border-tertiary-violet-50 active:border-tertiary-violet-50 placeholder:text-neutral-30 text-neutral-100 text-[11px] h-[33px] focus:shadow-none px-[14px] md:px-4 placeholder:!text-neutral-60</value>
      <webElementGuid>aa0737ae-2aa2-4f38-90b9-35c02e79514f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b69b4b1a-524e-4916-ad9a-99fbd6b37d74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>15</value>
      <webElementGuid>75442abd-1bb3-4b6c-ae6d-b1297dfd325b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mentor-onboarding_whatsapp</value>
      <webElementGuid>4a03577d-458a-4b29-9378-fe63b6c5bc58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mentor-onboarding_whatsapp&quot;)</value>
      <webElementGuid>d338113f-f26b-49fc-850c-222348cae260</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='mentor-onboarding_whatsapp']</value>
      <webElementGuid>ef06d26f-9814-4aa6-9745-ae95bf1ba396</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='mentor-onboarding']/div/div[3]/div[2]/div/div[3]/div/div/div/div/div/input</value>
      <webElementGuid>4b4fb715-f572-4c74-9edb-0ecb436f8979</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/div/input</value>
      <webElementGuid>df8433a1-06fe-479a-bb1e-278d64697904</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Whatsapp (mulai dengan kode negara, cth: 62)' and @type = 'text' and @id = 'mentor-onboarding_whatsapp']</value>
      <webElementGuid>617898d4-1746-48ee-b895-7ec10992cab4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
