<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Optional, max. 1MB_mentor-onboarding_email</name>
   <tag></tag>
   <elementGuidId>1f4a8dff-d5a7-4986-92cd-9ee3975e84d6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='mentor-onboarding_email']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mentor-onboarding_email</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a8712e03-6186-4f9e-b75a-f8c49ca52b93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Email</value>
      <webElementGuid>db32e2f7-ccad-43f8-b806-348eccd076c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-input py-0 rounded-md border border-neutral-15 bg-neutral-5 hover:border-tertiary-violet-50 focus:border-tertiary-violet-50 active:border-tertiary-violet-50 placeholder:text-neutral-30 text-neutral-100 text-[11px] h-[33px] focus:shadow-none px-[14px] md:px-4 placeholder:!text-neutral-60</value>
      <webElementGuid>a746c32c-de37-42e4-945c-c0df6f870e63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>10ed5db6-369e-4a23-bd09-42daeba71af8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mentor-onboarding_email</value>
      <webElementGuid>512f86b7-cbee-43cd-acaa-085c01f20a7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>c832f9a5-2a0c-444f-9fbf-02721dda4074</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mentor-onboarding_email&quot;)</value>
      <webElementGuid>93e9ba29-7cb5-4e78-8f92-286df14056b1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='mentor-onboarding_email']</value>
      <webElementGuid>649802f8-a5ac-4093-9e18-8a38e4cfc6d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='mentor-onboarding']/div/div[3]/div[2]/div/div[2]/div/div/div/div/div/input</value>
      <webElementGuid>06b216c8-2c0b-4859-9138-88eebb9ec793</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/input</value>
      <webElementGuid>dff279d2-256c-4407-9b1d-d62600e94745</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Email' and @type = 'text' and @id = 'mentor-onboarding_email']</value>
      <webElementGuid>f96fc54c-790e-493a-b390-b3abcbf16db1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
