<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Selanjutnya</name>
   <tag></tag>
   <elementGuidId>079d7b18-b205-4e92-82fb-52da6e8566d0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/main/div[3]/button[2]/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>3b243018-edb2-47e3-856f-2b134d9c3417</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Selanjutnya</value>
      <webElementGuid>81978281-365a-4d3c-aba5-6415c9ab8bd8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/main[@class=&quot;relative min-h-screen bg-neutral-5&quot;]/div[@class=&quot;z-30 flex w-full flex-col items-center justify-center gap-1 px-[34px] md:flex-row py-4 md:py-[30px] StickyButton_sticky_navbar_shadow__z0Mei fixed bottom-0 left-0 border-0 border-neutral-20 bg-white md:border-t-[1px]&quot;]/button[@class=&quot;ant-btn ant-btn-default order-1 w-full md:order-2 md:w-[176px] after:!shadow-none flex items-center justify-center font-bold active:!shadow-[3px_3px_0px_#000000] shadow-[3px_3px_0px_#000000] disabled:shadow-[3px_3px_0px_#000000] disabled:hover:shadow-[3px_3px_0px_#000000] disabled:cursor-not-allowed disabled:border-black disabled:bg-neutral-30 disabled:text-white disabled:hover:border-black disabled:hover:bg-neutral-30 disabled:hover:text-white border border-black hover:border-black focus:border-black active:border-black bg-tertiary-violet-50 text-white hover:bg-tertiary-violet-50 hover:text-white focus:bg-tertiary-violet-50 focus:text-white active:bg-tertiary-violet-50 active:text-white rounded-[71px] h-9 text-xs lg:h-11 lg:text-base&quot;]/span[1]</value>
      <webElementGuid>d9fec992-fd9a-45dc-b6cd-818565e5576b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/div[3]/button[2]/span</value>
      <webElementGuid>0c8a67ba-2143-433a-84ba-2de974618de3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kembali'])[1]/following::span[1]</value>
      <webElementGuid>3fea7175-0aaa-495b-a4e3-49a83ad1915c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Optional, max. 1MB'])[1]/following::span[2]</value>
      <webElementGuid>86153ddb-6484-4af1-bed2-f77ab74b745d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Butuh Bantuan ?'])[1]/preceding::span[1]</value>
      <webElementGuid>c0a0e314-17ff-4aef-a186-184fa7620521</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Selanjutnya']/parent::*</value>
      <webElementGuid>a281ec1a-8f38-4515-857f-a6be50079d80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]/span</value>
      <webElementGuid>bb36b188-fe1d-4462-8bfe-79019e894a08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Selanjutnya' or . = 'Selanjutnya')]</value>
      <webElementGuid>28b59a5d-b0b1-44a0-b935-a77c3503ea64</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
